name: test
on:
  pull_request:
  push:
    branches:
      - main
      - releases/*
  schedule:
    - cron: 0 19 * * 2

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
  integration_default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: run_myself
        continue-on-error: true
      - run: echo "${{steps.run_myself.outputs.output}}" | grep '"was stolen" may be passive voice on line 3 at column 11'
  integration_custom_path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          path: test/README_GOOD.md